<?php

namespace AppBundle\Repository;

/**
 * OfficialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfficialRepository extends \Doctrine\ORM\EntityRepository
{
}
