<?php

namespace AppBundle\Repository;

/**
 * OrdaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdaRepository extends \Doctrine\ORM\EntityRepository
{
}
