<?php

namespace AppBundle\Repository;

/**
 * ProspectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProspectRepository extends \Doctrine\ORM\EntityRepository
{
}
